import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import { Sidebar } from "@/components/layouts/Sidebar";
import { Header } from "@/components/layouts/Header";
import NextAuthProvider from "@/context/NextAuthProvider";
import { getServerSession } from "next-auth";
import authOptions from "@/lib/authOptions";
import { redirect } from "next/navigation";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  if (!session) {
    return redirect("/signin");
  }

  return (
    <html lang="en">
      <body className={poppins.className}>
        <NextAuthProvider>
          <main className="bg-background">
            <div className="grid grid-cols-5">
              <div className="hidden lg:block col-span-1">
                <div className="sticky top-0">
                  <Sidebar />
                </div>
              </div>
              <div className="overflow-auto col-span-5 lg:col-span-4 lg:border-l">
                <div className="px-6 py-6 lg:px-8">
                  <Header />
                  {children}
                </div>
              </div>
            </div>
          </main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
