import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/layouts/Sidebar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="bg-background">
          <div className="flex flex-row">
            <div className="hidden lg:block w-[18%]">
              <Sidebar />
            </div>
            <div className="col-span-3 overflow-auto lg:col-span-5 lg:border-l w-[82%]">
              <div className="px-6 py-6 lg:px-8">
                <div className="">header</div>
                {children}
              </div>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
